[uwsgi]
http = 0.0.0.0:8013
processes = 2
master = true
vacuum = true
no-orphans = true
lazy-apps = true
manage-script-name = true
max-requests = 1000
buffer-size = 32768
mount = /=awx.wsgi:application
harakiri = 120
py-call-osafterfork = true
